### ISSUE TITLE
FCSolar API Error

### ISSUE THREAD

**Issue by mrhahn3000** [muexxl/batcontrol_addon#1]
Hallo,

aktuell bekomme ich im Log von batcontrol folgende Exception:

`2023-11-28 21:56:49 INFO [FCSolar] Requesting Information for PV Installation Haus
2023-11-28 21:56:49 WARNING [BatCtrl] Following Exception occurred when trying to get forecasts: 
	max() arg is an empty sequence
2023-11-28 21:56:49 INFO [BatCtrl] An API Error occured 0s ago. Keeping inverter mode unchanged.`

Scheinbar hat sich die API von FCSolar geändert?! Ich habe es heute entdeckt, da ich checken wollte, ob aufgrund der Vorhersage für morgen (tibber Preis bis 46 ct) und der Wetterverhältnisse der Speicher heute Nacht geladen werden soll aus dem Netz mit 26 ct. 

Wird wohl heute nix.

Neustart des Addons hat nichts gebracht bislang.

Addon Version: 0.1.3
HA Core: 2023.11.3
HA Supervisor: 2023.11.3
Operating System: 11.1
Frontend: 20231030.2

**Comment by muexxl** [comment]
Hallo Kevin, 
die FCSolar API funktioniert bei mir auf jeden Fall. 
Du kannst du FC Solar API Mal direkt im Browser testen: 
```https://api.forecast.solar/estimate/watthours/period/{lat}/{lon}/{dec}/{az}/{kwp}```
Du kannst Werte in {}-Klammern einfach durch die entsprechenden Werte in deiner batcontrol_config.yaml ersetzen und in deinen Browser eingeben um einen GET request zu testen. 
Kommt da ein Error?

**Comment by mrhahn3000** [comment]
Hallo Stephan,

vielen Dank für die schnelle Antwort. Tatsächlich war das nun irgendwie Self-healing. Hab gerade reingeschaut und die Werte passen wieder. Das Array hat wieder Werte und die Modes für battery werden wieder richtig gesetzt.

Ich beobachte das mal weiter, warum es hier spontan zu einem Fehler kam.

Vielen Dank für deine Arbeit!

Viele Grüße,
Kevin

**Comment by muexxl** [comment]
Self healing code. So mag ich das :)
Noch besser wäre nur non-breaking code.
