### ISSUE TITLE
Falsche Zeitzone trotz Berlin?

### ISSUE THREAD

**Issue by PhilippBLG** [muexxl/batcontrol_addon#3]
![image](https://github.com/user-attachments/assets/ff6a04e7-a4c9-4549-aa26-e295a0170298)

Wie im Screenshot zu sehen ist es aktuell eigentlich 18:54, der Log der Batcontrol zeigt mir jedoch dauerhaft eine Stunde versetzt. Sowohl die Zeitzone im HA als auch in der Batcontrol selber sind richtig eingestellt.

**Comment by muexxl** [comment]
Hi Philipp, 

danke für deine Beobachtung. 

tatsächlich arbeitet die Logik von Batcontrol mit der von dir in der config angegebenen Zeitzone. Das Loggingmodul nutzt jedoch die Systemzeit von dem Container in welchem batcontrol läuft. Diese ist leider nicht so einfach zu korrigieren. Dadurch haben die Ausgaben leider auf manchen Systemen eine Abweichung. 

Es ist also nur ein wenig irritierend, aber die eigentliche Funktion ist nicht beeinträchtigt. 

Ich lass das mal offen.. kann man sich bei Gelegenheit mal anschauen. 

VG -- Muexxl

**Comment by muexxl** [comment]
update ist raus. In 0.2.8. wird die angegebenen Zeitzone auch für das logging übernommen.
